### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by bbieberle** [epiception/SGM-Census#2]
Hi, 

i am currently working on my bachelor thesis and very happy to have your code of the sgbm algorithm available. Could you please add a license, so i can reference it correctly for further use.

Sincerely,
Benedikt

**Comment by epiception** [comment]
Hey!
Sorry for the delay, hope you're using it already.

**Comment by bbieberle** [comment]
Thank you very much mate!   
  
  
  

  
  
  
  
  
>
