### ISSUE TITLE
Faulty aggregation start

### ISSUE THREAD

**Issue by bbieberle** [epiception/SGM-Census#3]
Hello Ganesh,

thanks again, that i am allowed to use your code in my bachelor thesis. I found a little mistake in this line. I think it should be window_height.

https://github.com/epiception/SGM-Census/blob/8b206450ecc63b312095041c2e903d6dd8ea8cc6/sgm.cpp#L109

Thanks and best regards,
Benedikt

**Comment by epiception** [comment]
Hi Benedikt,

You're right! This is a silly mistake on my end. That did remove a few artifacts in the output.

Mistake: 
![image](https://user-images.githubusercontent.com/13215333/53377960-e33b3600-3931-11e9-875c-a7c15c89878b.png)

Correct one:
![image](https://user-images.githubusercontent.com/13215333/53377990-fbab5080-3931-11e9-9736-ced1d2c223c7.png)

Do you want to make a pull request?

**Comment by epiception** [comment]
Corrected #4
