### ISSUE TITLE
How can I get a good result

### ISSUE THREAD

**Issue by 1868236** [epiception/SGM-Census#5]
When I set  disparity range=64, the disparity map of teddy was really bad

![disp](https://user-images.githubusercontent.com/29472382/55005740-7e99f680-5017-11e9-8db9-9051e645804d.png)

Thanks and best regards

**Comment by epiception** [comment]
Did you provide the images in the wrong order by mistake?

**Comment by 1868236** [comment]
oh, it's my fault
thanks
